<?xml version="1.0" ?>
<!DOCTYPE schema_er [ <!ELEMENT schema_er (le_entita, le_relazioni, le_generalizzazioni, note)> <!ELEMENT documentazione (#PCDATA)><!ELEMENT vincoli (#PCDATA)><!ELEMENT altro (#PCDATA)><!ELEMENT le_entita (entita)*><!ELEMENT le_relazioni (relazione)*><!ELEMENT le_generalizzazioni (generalizzazione)*>  <!ELEMENT note (documentazione, vincoli, altro) > <!ELEMENT entita (nome, attributo+,idesterna,note)><!ATTLIST entita id ID #REQUIRED> <!ELEMENT nome (#PCDATA)><!ELEMENT idesterna (#PCDATA)> <!ELEMENT attributo (#PCDATA)><!ATTLIST attributo chiave ID #REQUIRED> <!ELEMENT Rel (nome, associazioni+, note)><!ELEMENT associazioni (associazione)*> <!ELEMENT associazione (entitacoll,molteplicita)> <!ELEMENT entitacoll (#PCDATA)><!ATTLIST entitacoll href IDREF #REQUIRED> <!ELEMENT molteplicita (#PCDATA)> <!ELEMENT generalizzazione (padre, figlio+, completa, note)><!ELEMENT padre (#PCDATA)><!ATTLIST padre href IDREF #REQUIRED> <!ELEMENT figlio (#PCDATA)><!ATTLIST figlio href IDREF #REQUIRED> <!ELEMENT completa (#PCDATA)> ]>
<schema_er>
	<le_entita>
		<entita id="1">
			<nome>ASSOCIAZIONE</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="2">
			<nome>FORNITORE</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="3">
			<nome>PACCHETTO</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="4">
			<nome>TIPO_UTENTE</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="5">
			<nome>CORSO</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="6">
			<nome>ANAGRAFICA_UTENTE</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="7">
			<nome>TRANSAZIONE</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="8">
			<nome>TESSERA</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="9">
			<nome>ISCRIZIONE_ASSOCIAZIONE</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="10">
			<nome>DATI_FISCALI</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="11">
			<nome>DISCIPLINA</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="12">
			<nome>SALA</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="13">
			<nome>PROGRAMMAZIONE</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="26">
			<nome>UTENTE</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
	</le_entita>
	<le_relazioni>
		<relazione>
			<nome>ASSOCIA</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>UTENZA</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>ISCRITTO</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>IMPEGNA</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>AFFERISCE</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>POSSIEDE</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>CONTABILIZZA</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>INCLUDE</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>RICEVE</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>EFFETTUA</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>FREQUENTA</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>COMPONE</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>COMPILA</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
	</le_relazioni>
	<le_generalizzazioni>
	</le_generalizzazioni>
	<note>
		<documentazione></documentazione>
		<vincoli></vincoli>
		<altro></altro>
	</note>
</schema_er>