<?xml version="1.0" ?>
<!DOCTYPE schema_er [ <!ELEMENT schema_er (le_entita, le_relazioni, le_generalizzazioni, note)> <!ELEMENT documentazione (#PCDATA)><!ELEMENT vincoli (#PCDATA)><!ELEMENT altro (#PCDATA)><!ELEMENT le_entita (entita)*><!ELEMENT le_relazioni (relazione)*><!ELEMENT le_generalizzazioni (generalizzazione)*>  <!ELEMENT note (documentazione, vincoli, altro) > <!ELEMENT entita (nome, attributo+,idesterna,note)><!ATTLIST entita id ID #REQUIRED> <!ELEMENT nome (#PCDATA)><!ELEMENT idesterna (#PCDATA)> <!ELEMENT attributo (#PCDATA)><!ATTLIST attributo chiave ID #REQUIRED> <!ELEMENT Rel (nome, associazioni+, note)><!ELEMENT associazioni (associazione)*> <!ELEMENT associazione (entitacoll,molteplicita)> <!ELEMENT entitacoll (#PCDATA)><!ATTLIST entitacoll href IDREF #REQUIRED> <!ELEMENT molteplicita (#PCDATA)> <!ELEMENT generalizzazione (padre, figlio+, completa, note)><!ELEMENT padre (#PCDATA)><!ATTLIST padre href IDREF #REQUIRED> <!ELEMENT figlio (#PCDATA)><!ATTLIST figlio href IDREF #REQUIRED> <!ELEMENT completa (#PCDATA)> ]>
<schema_er>
	<le_entita>
		<entita id="1">
			<nome>iscritto</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="2">
			<nome>utente_sito</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="3">
			<nome>corso</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="4">
			<nome>asd</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="5">
			<nome>transazione</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="6">
			<nome>sala</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="7">
			<nome>disciplina</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="8">
			<nome>programmazione</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="9">
			<nome>pacchetto</nome>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
	</le_entita>
	<le_relazioni>
		<relazione>
			<nome>iscrizione</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>registra</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>corrisponde</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>costituito</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>definisce</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>dipende</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>impegna</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>associa</nome>
			<associazioni>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
	</le_relazioni>
	<le_generalizzazioni>
	</le_generalizzazioni>
	<note>
		<documentazione></documentazione>
		<vincoli></vincoli>
		<altro></altro>
	</note>
</schema_er>