<?xml version="1.0" ?>
<!DOCTYPE schema_er [ <!ELEMENT schema_er (le_entita, le_relazioni, le_generalizzazioni, note)> <!ELEMENT documentazione (#PCDATA)><!ELEMENT vincoli (#PCDATA)><!ELEMENT altro (#PCDATA)><!ELEMENT le_entita (entita)*><!ELEMENT le_relazioni (relazione)*><!ELEMENT le_generalizzazioni (generalizzazione)*>  <!ELEMENT note (documentazione, vincoli, altro) > <!ELEMENT entita (nome, attributo+,idesterna,note)><!ATTLIST entita id ID #REQUIRED> <!ELEMENT nome (#PCDATA)><!ELEMENT idesterna (#PCDATA)> <!ELEMENT attributo (#PCDATA)><!ATTLIST attributo chiave ID #REQUIRED> <!ELEMENT Rel (nome, associazioni+, note)><!ELEMENT associazioni (associazione)*> <!ELEMENT associazione (entitacoll,molteplicita)> <!ELEMENT entitacoll (#PCDATA)><!ATTLIST entitacoll href IDREF #REQUIRED> <!ELEMENT molteplicita (#PCDATA)> <!ELEMENT generalizzazione (padre, figlio+, completa, note)><!ELEMENT padre (#PCDATA)><!ATTLIST padre href IDREF #REQUIRED> <!ELEMENT figlio (#PCDATA)><!ATTLIST figlio href IDREF #REQUIRED> <!ELEMENT completa (#PCDATA)> ]>
<schema_er>
	<le_entita>
		<entita id="1">
			<nome>ASSOCIAZIONE</nome>
			<attributo chiave="true">id_associazione</attributo>
			<attributo chiave="false">nome</attributo>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="2">
			<nome>FORNITORE_ANAGRAFICA</nome>
			<attributo chiave="false">id_fornitore</attributo>
			<attributo chiave="false">nome</attributo>
			<attributo chiave="false">ragione_sociale</attributo>
			<attributo chiave="false">indirizzo</attributo>
			<attributo chiave="false">cap</attributo>
			<attributo chiave="false">città</attributo>
			<attributo chiave="false">provincia</attributo>
			<attributo chiave="false">tipologia_fornitura</attributo>
			<attributo chiave="false">note</attributo>
			<idesterna>true</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="3">
			<nome>PACCHETTO</nome>
			<attributo chiave="true">id_pacco</attributo>
			<attributo chiave="false">nome_pacco</attributo>
			<attributo chiave="false">prezzo</attributo>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="4">
			<nome>TIPO_UTENTE</nome>
			<attributo chiave="true">id_tipo</attributo>
			<attributo chiave="false">tipo_utente</attributo>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="5">
			<nome>CORSO</nome>
			<attributo chiave="true">id_corso</attributo>
			<attributo chiave="false">nome_corso</attributo>
			<attributo chiave="false">costo_orario</attributo>
			<idesterna>true</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="6">
			<nome>ANAGRAFICA_UTENTE</nome>
			<attributo chiave="true">id_anagrafica</attributo>
			<attributo chiave="false">nome</attributo>
			<attributo chiave="false">cognome</attributo>
			<attributo chiave="false">indirizzo</attributo>
			<attributo chiave="false">cap</attributo>
			<attributo chiave="false">citta</attributo>
			<attributo chiave="false">provincia</attributo>
			<attributo chiave="false">genere</attributo>
			<attributo chiave="false">luogo_nascita</attributo>
			<attributo chiave="false">data_nascita</attributo>
			<attributo chiave="false">socio</attributo>
			<idesterna>true</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="7">
			<nome>TRANSAZIONE</nome>
			<attributo chiave="true">id_transazione</attributo>
			<attributo chiave="false">tipo</attributo>
			<attributo chiave="false">importo</attributo>
			<attributo chiave="false">data_creazione</attributo>
			<attributo chiave="false">descrizione</attributo>
			<attributo chiave="false">file_fattura</attributo>
			<idesterna>true</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="8">
			<nome>TESSERA</nome>
			<attributo chiave="true">id_tessera</attributo>
			<attributo chiave="false">num_tessera</attributo>
			<attributo chiave="false">scad_tessera</attributo>
			<idesterna>true</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="9">
			<nome>ISCRIZIONE_ASSOCIAZIONE</nome>
			<attributo chiave="true">id_iscrizione</attributo>
			<attributo chiave="false">cod_fisc</attributo>
			<attributo chiave="false">num_cell</attributo>
			<attributo chiave="false">num_tel</attributo>
			<attributo chiave="false">data_stipula</attributo>
			<attributo chiave="false">scadenza_assic</attributo>
			<attributo chiave="false">num_assic</attributo>
			<attributo chiave="false">data_rilascio_certif_med</attributo>
			<attributo chiave="false">data_scad_cerif_med</attributo>
			<attributo chiave="false">ruolo</attributo>
			<attributo chiave="false">P.IVA</attributo>
			<attributo chiave="false">note</attributo>
			<idesterna>true</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="10">
			<nome>DATI_FISCALI</nome>
			<attributo chiave="false">flag</attributo>
			<attributo chiave="true">id_iscrizione</attributo>
			<attributo chiave="false">imp_paga</attributo>
			<attributo chiave="false">mod_paga</attributo>
			<attributo chiave="false">descrizione</attributo>
			<attributo chiave="false">data_iscrizione</attributo>
			<attributo chiave="false">tipo_ricevuta</attributo>
			<attributo chiave="false">num_doc_fisc</attributo>
			<idesterna>true</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="11">
			<nome>DISCIPLINA</nome>
			<attributo chiave="true">id_disciplina</attributo>
			<attributo chiave="false">nome_discipl</attributo>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="12">
			<nome>SALA</nome>
			<attributo chiave="true">nome</attributo>
			<idesterna>false</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="13">
			<nome>PROGRAMMAZIONE</nome>
			<attributo chiave="true">id_progr</attributo>
			<attributo chiave="false">data</attributo>
			<idesterna>true</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
		<entita id="26">
			<nome>UTENTE</nome>
			<attributo chiave="true">Id_utente</attributo>
			<attributo chiave="false">email</attributo>
			<attributo chiave="false">password</attributo>
			<idesterna>true</idesterna>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</entita>
	</le_entita>
	<le_relazioni>
		<relazione>
			<nome>ASSOCIA</nome>
			<associazioni>
				<associazione>
					<entitacoll href="3">PACCHETTO</entitacoll>
					<molteplicita>(1,N)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="5">CORSO</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>UTENZA</nome>
			<associazioni>
				<associazione>
					<entitacoll href="4">TIPO_UTENTE</entitacoll>
					<molteplicita>(1,N)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="6">ANAGRAFICA_UTENTE</entitacoll>
					<molteplicita>(1,N)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>ISCRITTO</nome>
			<associazioni>
				<associazione>
					<entitacoll href="6">ANAGRAFICA_UTENTE</entitacoll>
					<molteplicita>(0,1)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="9">ISCRIZIONE_ASSOCIAZIONE</entitacoll>
					<molteplicita>(1,1)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>IMPEGNA</nome>
			<associazioni>
				<associazione>
					<entitacoll href="13">PROGRAMMAZIONE</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="12">SALA</entitacoll>
					<molteplicita>(1,N)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>AFFERISCE</nome>
			<associazioni>
				<associazione>
					<entitacoll href="11">DISCIPLINA</entitacoll>
					<molteplicita>(1,N)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="5">CORSO</entitacoll>
					<molteplicita>(1,1)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>POSSIEDE</nome>
			<associazioni>
				<associazione>
					<entitacoll href="6">ANAGRAFICA_UTENTE</entitacoll>
					<molteplicita>(0,1)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="8">TESSERA</entitacoll>
					<molteplicita>(1,1)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>INCLUDE</nome>
			<associazioni>
				<associazione>
					<entitacoll href="6">ANAGRAFICA_UTENTE</entitacoll>
					<molteplicita>(0,1)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="10">DATI_FISCALI</entitacoll>
					<molteplicita>(1,1)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>RICEVE</nome>
			<associazioni>
				<associazione>
					<entitacoll href="2">FORNITORE_ANAGRAFICA</entitacoll>
					<molteplicita>(1,N)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="7">TRANSAZIONE</entitacoll>
					<molteplicita>(1,N)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>EFFETTUA</nome>
			<associazioni>
				<associazione>
					<entitacoll href="6">ANAGRAFICA_UTENTE</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="7">TRANSAZIONE</entitacoll>
					<molteplicita>(1,N)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>ASSOCIATO</nome>
			<associazioni>
				<associazione>
					<entitacoll href="6">ANAGRAFICA_UTENTE</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="5">CORSO</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>COMPONE</nome>
			<associazioni>
				<associazione>
					<entitacoll href="5">CORSO</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="13">PROGRAMMAZIONE</entitacoll>
					<molteplicita>(1,1)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>COMPILA</nome>
			<associazioni>
				<associazione>
					<entitacoll href="6">ANAGRAFICA_UTENTE</entitacoll>
					<molteplicita>(1,1)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="26">UTENTE</entitacoll>
					<molteplicita>(1,1)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>CONTABILIZZA</nome>
			<associazioni>
				<associazione>
					<entitacoll href="7">TRANSAZIONE</entitacoll>
					<molteplicita>(1,1)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="1">ASSOCIAZIONE</entitacoll>
					<molteplicita>(0,N)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
		<relazione>
			<nome>F_A</nome>
			<associazioni>
				<associazione>
					<entitacoll href="9">ISCRIZIONE_ASSOCIAZIONE</entitacoll>
					<molteplicita>(0,1)</molteplicita>
				</associazione>
				<associazione>
					<entitacoll href="2">FORNITORE_ANAGRAFICA</entitacoll>
					<molteplicita>(1,1)</molteplicita>
				</associazione>
			</associazioni>
			<note>
				<documentazione></documentazione>
				<vincoli></vincoli>
				<altro></altro>
			</note>
		</relazione>
	</le_relazioni>
	<le_generalizzazioni>
	</le_generalizzazioni>
	<note>
		<documentazione></documentazione>
		<vincoli></vincoli>
		<altro></altro>
	</note>
</schema_er>